import 'package:flutter/material.dart';

class LanguageOption {
  final String code;
  final String englishName;
  final String nativeName;
  final String flag; // emoji flag — koi image asset zaroorat nahi
  const LanguageOption({
    required this.code,
    required this.englishName,
    required this.nativeName,
    required this.flag,
  });
}

// App ke saare supported languages ek jagah — main.dart (Multilingual
// widget setup) aur language picker (settings/permission) dono yahi se
// list uthate hai. Naya language add karna ho toh sirf yaha add karo.
//
// UI strings yaha keys ke roop me hai — screens me 'key'.trans() use karo,
// hardcoded Text('...') nahi. Ye keys sirf un screens ke liye hai jo abhi
// app me actually maujood hai (splash/permission/privacy/language/onboarding/
// gender-age-category home) — purani SMS-app wali unused keys hata di.
class AppLanguages {
  static const Map<String, String> labels = {
    'en': 'English',
    'hi': 'हिन्दी',
    'ar': 'العربية',
    'bn': 'বাংলা',
    'zh': '中文',
    'fr': 'Français',
    'de': 'Deutsch',
    'id': 'Bahasa Indonesia',
    'it': 'Italiano',
    'ja': '日本語',
    'ko': '한국어',
    'pl': 'Polski',
    'pt': 'Português',
    'ro': 'Română',
    'es': 'Español',
    'sw': 'Kiswahili',
    'th': 'ไทย',
    'ur': 'اردو',
    'vi': 'Tiếng Việt',
  };

  // Language screen (flag/native-name/radio list) ke liye metadata.
  static const List<LanguageOption> options = [
    LanguageOption(code: 'en', englishName: 'English', nativeName: 'English', flag: '\u{1F1FA}\u{1F1F8}'),
    LanguageOption(code: 'ar', englishName: 'Arabic', nativeName: 'العربية', flag: '\u{1F1F8}\u{1F1E6}'),
    LanguageOption(code: 'bn', englishName: 'Bengali', nativeName: 'বাংলা', flag: '\u{1F1E7}\u{1F1E9}'),
    LanguageOption(code: 'zh', englishName: 'Chinese', nativeName: '中文', flag: '\u{1F1E8}\u{1F1F3}'),
    LanguageOption(code: 'fr', englishName: 'French', nativeName: 'Français', flag: '\u{1F1EB}\u{1F1F7}'),
    LanguageOption(code: 'de', englishName: 'German', nativeName: 'Deutsch', flag: '\u{1F1E9}\u{1F1EA}'),
    LanguageOption(code: 'hi', englishName: 'Hindi', nativeName: 'हिन्दी', flag: '\u{1F1EE}\u{1F1F3}'),
    LanguageOption(code: 'id', englishName: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '\u{1F1EE}\u{1F1E9}'),
    LanguageOption(code: 'it', englishName: 'Italian', nativeName: 'Italiano', flag: '\u{1F1EE}\u{1F1F9}'),
    LanguageOption(code: 'ja', englishName: 'Japanese', nativeName: '日本語', flag: '\u{1F1EF}\u{1F1F5}'),
    LanguageOption(code: 'ko', englishName: 'Korean', nativeName: '한국어', flag: '\u{1F1F0}\u{1F1F7}'),
    LanguageOption(code: 'pl', englishName: 'Polish', nativeName: 'Polski', flag: '\u{1F1F5}\u{1F1F1}'),
    LanguageOption(code: 'pt', englishName: 'Portuguese', nativeName: 'Português', flag: '\u{1F1F5}\u{1F1F9}'),
    LanguageOption(code: 'ro', englishName: 'Romanian', nativeName: 'Română', flag: '\u{1F1F7}\u{1F1F4}'),
    LanguageOption(code: 'es', englishName: 'Spanish', nativeName: 'Español', flag: '\u{1F1EA}\u{1F1F8}'),
    LanguageOption(code: 'sw', englishName: 'Swahili', nativeName: 'Kiswahili', flag: '\u{1F1F0}\u{1F1EA}'),
    LanguageOption(code: 'th', englishName: 'Thai', nativeName: 'ไทย', flag: '\u{1F1F9}\u{1F1ED}'),
    LanguageOption(code: 'ur', englishName: 'Urdu', nativeName: 'اردو', flag: '\u{1F1F5}\u{1F1F0}'),
    LanguageOption(code: 'vi', englishName: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '\u{1F1FB}\u{1F1F3}'),
  ];

  static final Map<Locale, Map<String, dynamic>> data = {
    const Locale('en', 'US'): {
      'lan': 'English',
      'select_language': 'Select language',
      'perm_title': 'Permission',
      'perm_heading': 'Read And Write Permission',
      'perm_subtitle': 'This app needs storage permission to access your image library. Without this permission, the application couldn\'t run properly.',
      'allow_access': 'Allow Access',
      'privacy_title': 'Privacy Policy',
      'privacy_intro': 'When you use our application, this Privacy Policy describes the information collected by us and how we use that information. Your privacy is important to us.',
      'privacy_notif_title': 'Notifications',
      'privacy_notif_body': 'This permission is used to send you reminders and important updates.',
      'privacy_photos_title': 'Photos and Videos',
      'privacy_photos_body': 'This permission allows the app to access your device\'s photo and video library so the app can run properly.',
      'privacy_network_title': 'Full network access',
      'privacy_network_body': 'Used to receive update notifications and access app classification labels.',
      'privacy_agree_checkbox': 'I read and accepted the privacy policy',
      'agree_next': 'Agree & Next',
      'onboard_title_1': 'XVX 4K Video Downloader',
      'onboard_sub_1': 'Download videos from various platform',
      'onboard_title_2': 'Paste & Download',
      'onboard_sub_2': 'Paste a link and download videos',
      'onboard_title_3': '3X Faster Download',
      'onboard_sub_3': 'Download videos 3x faster that usual',
      'personalized_title': 'Personalized Information',
      'personalized_subtitle': 'Get Updates and content tailored just for you',
      'select_gender': 'Select Gender',
      'gender_female': 'Female',
      'gender_male': 'Male',
      'gender_warning': 'Once you select your gender, it cannot be changed! Make sure to choose carefully before proceeding.',
      'select_age_range': 'Select Age Range',
      'select_age_subtitle': 'Pick an age range to discover people or content that suits you best',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'Select Category',
      'select_category_subtitle': 'Select category to discover people or content that suits you best',
      'cat_all_video': 'All Video Download',
      'cat_insta': 'Insta Download',
      'cat_fb': 'FB Download',
      'cat_tiktok': 'Tik Tok Download',
      'cat_twitter': 'Twitter Download',
      'next_btn': 'Next',
      'home_disclaimer': 'This app does not host any content. All downloads are from publicly shared links.',
      'link_hint': 'Paste video link here',
      'paste_btn': 'Paste',
      'download_btn': 'Download',
      'supported_socials': 'Supported Socials',
      'how_to_download': 'How to Download?',
      'downloads_title': 'Downloads',
      'downloads_empty': 'No downloads yet',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': 'Photos',
      'media_video': 'Video',
    },
    const Locale('hi', 'IN'): {
      'lan': 'हिन्दी',
      'select_language': 'भाषा चुनें',
      'perm_title': 'अनुमति',
      'perm_heading': 'पढ़ने और लिखने की अनुमति',
      'perm_subtitle': 'इस ऐप को आपकी इमेज लाइब्रेरी एक्सेस करने के लिए स्टोरेज अनुमति चाहिए। इस अनुमति के बिना ऐप सही से नहीं चल पाएगा।',
      'allow_access': 'अनुमति दें',
      'privacy_title': 'गोपनीयता नीति',
      'privacy_intro': 'जब आप हमारा ऐप इस्तेमाल करते हैं, यह गोपनीयता नीति बताती है कि हम कौन सी जानकारी इकट्ठा करते हैं और उसका उपयोग कैसे करते हैं। आपकी गोपनीयता हमारे लिए महत्वपूर्ण है।',
      'privacy_notif_title': 'सूचनाएं',
      'privacy_notif_body': 'इस अनुमति का उपयोग आपको रिमाइंडर और जरूरी अपडेट भेजने के लिए किया जाता है।',
      'privacy_photos_title': 'फोटो और वीडियो',
      'privacy_photos_body': 'यह अनुमति ऐप को आपके डिवाइस की फोटो और वीडियो लाइब्रेरी एक्सेस करने देती है ताकि ऐप सही से चल सके।',
      'privacy_network_title': 'पूरी नेटवर्क पहुंच',
      'privacy_network_body': 'अपडेट नोटिफिकेशन पाने और ऐप क्लासिफिकेशन लेबल एक्सेस करने के लिए उपयोग होता है।',
      'privacy_agree_checkbox': 'मैंने गोपनीयता नीति पढ़ ली है और स्वीकार करता हूं',
      'agree_next': 'स्वीकार करें और आगे बढ़ें',
      'onboard_title_1': 'XVX 4K वीडियो डाउनलोडर',
      'onboard_sub_1': 'विभिन्न प्लेटफॉर्म से वीडियो डाउनलोड करें',
      'onboard_title_2': 'पेस्ट करें और डाउनलोड करें',
      'onboard_sub_2': 'लिंक पेस्ट करें और वीडियो डाउनलोड करें',
      'onboard_title_3': '3 गुना तेज़ डाउनलोड',
      'onboard_sub_3': 'सामान्य से 3 गुना तेज़ वीडियो डाउनलोड करें',
      'personalized_title': 'व्यक्तिगत जानकारी',
      'personalized_subtitle': 'अपने लिए तैयार अपडेट और कंटेंट पाएं',
      'select_gender': 'लिंग चुनें',
      'gender_female': 'महिला',
      'gender_male': 'पुरुष',
      'gender_warning': 'एक बार लिंग चुनने के बाद इसे बदला नहीं जा सकता! आगे बढ़ने से पहले ध्यान से चुनें।',
      'select_age_range': 'आयु सीमा चुनें',
      'select_age_subtitle': 'अपने लिए सही लोग या कंटेंट खोजने के लिए एक आयु सीमा चुनें',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'श्रेणी चुनें',
      'select_category_subtitle': 'अपने लिए सही लोग या कंटेंट खोजने के लिए श्रेणी चुनें',
      'cat_all_video': 'सभी वीडियो डाउनलोड',
      'cat_insta': 'इंस्टा डाउनलोड',
      'cat_fb': 'एफबी डाउनलोड',
      'cat_tiktok': 'टिक टॉक डाउनलोड',
      'cat_twitter': 'ट्विटर डाउनलोड',
      'next_btn': 'आगे',
      'home_disclaimer': 'यह ऐप कोई कंटेंट होस्ट नहीं करता। सभी डाउनलोड सार्वजनिक रूप से साझा किए गए लिंक से हैं।',
      'link_hint': 'यहां वीडियो लिंक पेस्ट करें',
      'paste_btn': 'पेस्ट करें',
      'download_btn': 'डाउनलोड करें',
      'supported_socials': 'समर्थित सोशल',
      'how_to_download': 'कैसे डाउनलोड करें?',
      'downloads_title': 'डाउनलोड्स',
      'downloads_empty': 'अभी कोई डाउनलोड नहीं',
      'social_facebook': 'फेसबुक',
      'social_instagram': 'इंस्टाग्राम',
      'social_whatsapp': 'व्हाट्सएप',
      'social_pinterest': 'पिनटरेस्ट',
      'media_photos': 'फ़ोटो',
      'media_video': 'वीडियो',
    },
    const Locale('ar', 'SA'): {
      'lan': 'العربية',
      'select_language': 'اختر اللغة',
      'perm_title': 'الإذن',
      'perm_heading': 'إذن القراءة والكتابة',
      'perm_subtitle': 'يحتاج هذا التطبيق إلى إذن التخزين للوصول إلى مكتبة الصور الخاصة بك. بدون هذا الإذن لن يعمل التطبيق بشكل صحيح.',
      'allow_access': 'السماح بالوصول',
      'privacy_title': 'سياسة الخصوصية',
      'privacy_intro': 'عند استخدامك لتطبيقنا، تصف سياسة الخصوصية هذه المعلومات التي نجمعها وكيفية استخدامنا لها. خصوصيتك مهمة بالنسبة لنا.',
      'privacy_notif_title': 'الإشعارات',
      'privacy_notif_body': 'يُستخدم هذا الإذن لإرسال تذكيرات وتحديثات مهمة لك.',
      'privacy_photos_title': 'الصور والفيديوهات',
      'privacy_photos_body': 'يسمح هذا الإذن للتطبيق بالوصول إلى مكتبة الصور والفيديو على جهازك ليعمل التطبيق بشكل صحيح.',
      'privacy_network_title': 'الوصول الكامل للشبكة',
      'privacy_network_body': 'يُستخدم لتلقي إشعارات التحديث والوصول إلى تصنيفات التطبيق.',
      'privacy_agree_checkbox': 'لقد قرأت ووافقت على سياسة الخصوصية',
      'agree_next': 'موافقة والمتابعة',
      'onboard_title_1': 'XVX لتحميل الفيديو 4K',
      'onboard_sub_1': 'قم بتحميل الفيديوهات من منصات مختلفة',
      'onboard_title_2': 'الصق وحمّل',
      'onboard_sub_2': 'الصق الرابط وحمّل الفيديوهات',
      'onboard_title_3': 'تحميل أسرع 3 مرات',
      'onboard_sub_3': 'حمّل الفيديوهات أسرع 3 مرات من المعتاد',
      'personalized_title': 'معلومات مخصصة',
      'personalized_subtitle': 'احصل على تحديثات ومحتوى مخصص لك',
      'select_gender': 'اختر الجنس',
      'gender_female': 'أنثى',
      'gender_male': 'ذكر',
      'gender_warning': 'بمجرد اختيار جنسك، لا يمكن تغييره! تأكد من الاختيار بعناية قبل المتابعة.',
      'select_age_range': 'اختر الفئة العمرية',
      'select_age_subtitle': 'اختر فئة عمرية لاكتشاف الأشخاص أو المحتوى الذي يناسبك',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'اختر الفئة',
      'select_category_subtitle': 'اختر فئة لاكتشاف الأشخاص أو المحتوى الذي يناسبك',
      'cat_all_video': 'تحميل جميع الفيديوهات',
      'cat_insta': 'تحميل من إنستغرام',
      'cat_fb': 'تحميل من فيسبوك',
      'cat_tiktok': 'تحميل من تيك توك',
      'cat_twitter': 'تحميل من تويتر',
      'next_btn': 'التالي',
      'home_disclaimer': 'هذا التطبيق لا يستضيف أي محتوى. جميع التنزيلات من روابط تمت مشاركتها علنًا.',
      'link_hint': 'الصق رابط الفيديو هنا',
      'paste_btn': 'لصق',
      'download_btn': 'تنزيل',
      'supported_socials': 'المنصات المدعومة',
      'how_to_download': 'كيفية التنزيل؟',
      'downloads_title': 'التنزيلات',
      'downloads_empty': 'لا توجد تنزيلات بعد',
      'social_facebook': 'فيسبوك',
      'social_instagram': 'إنستغرام',
      'social_whatsapp': 'واتساب',
      'social_pinterest': 'بينتيريست',
      'media_photos': 'الصور',
      'media_video': 'فيديو',
    },
    const Locale('bn', 'BD'): {
      'lan': 'বাংলা',
      'select_language': 'ভাষা নির্বাচন করুন',
      'perm_title': 'অনুমতি',
      'perm_heading': 'পড়া এবং লেখার অনুমতি',
      'perm_subtitle': 'আপনার ইমেজ লাইব্রেরি অ্যাক্সেস করতে এই অ্যাপের স্টোরেজ অনুমতি প্রয়োজন। এই অনুমতি ছাড়া অ্যাপটি সঠিকভাবে চলবে না।',
      'allow_access': 'অ্যাক্সেসের অনুমতি দিন',
      'privacy_title': 'গোপনীয়তা নীতি',
      'privacy_intro': 'আপনি যখন আমাদের অ্যাপ ব্যবহার করেন, এই গোপনীয়তা নীতি বর্ণনা করে আমরা কী তথ্য সংগ্রহ করি এবং কীভাবে তা ব্যবহার করি। আপনার গোপনীয়তা আমাদের কাছে গুরুত্বপূর্ণ।',
      'privacy_notif_title': 'বিজ্ঞপ্তি',
      'privacy_notif_body': 'এই অনুমতি আপনাকে রিমাইন্ডার ও গুরুত্বপূর্ণ আপডেট পাঠাতে ব্যবহৃত হয়।',
      'privacy_photos_title': 'ছবি ও ভিডিও',
      'privacy_photos_body': 'এই অনুমতি অ্যাপটিকে আপনার ডিভাইসের ছবি ও ভিডিও লাইব্রেরি অ্যাক্সেস করতে দেয় যাতে অ্যাপ সঠিকভাবে চলতে পারে।',
      'privacy_network_title': 'সম্পূর্ণ নেটওয়ার্ক অ্যাক্সেস',
      'privacy_network_body': 'আপডেট বিজ্ঞপ্তি পাওয়া এবং অ্যাপ শ্রেণিবিন্যাস লেবেল অ্যাক্সেস করতে ব্যবহৃত হয়।',
      'privacy_agree_checkbox': 'আমি গোপনীয়তা নীতি পড়েছি এবং গ্রহণ করেছি',
      'agree_next': 'সম্মত ও পরবর্তী',
      'onboard_title_1': 'XVX 4K ভিডিও ডাউনলোডার',
      'onboard_sub_1': 'বিভিন্ন প্ল্যাটফর্ম থেকে ভিডিও ডাউনলোড করুন',
      'onboard_title_2': 'পেস্ট এবং ডাউনলোড',
      'onboard_sub_2': 'একটি লিঙ্ক পেস্ট করুন এবং ভিডিও ডাউনলোড করুন',
      'onboard_title_3': '৩ গুণ দ্রুত ডাউনলোড',
      'onboard_sub_3': 'সাধারণের চেয়ে ৩ গুণ দ্রুত ভিডিও ডাউনলোড করুন',
      'personalized_title': 'ব্যক্তিগতকৃত তথ্য',
      'personalized_subtitle': 'আপনার জন্য তৈরি আপডেট ও কনটেন্ট পান',
      'select_gender': 'লিঙ্গ নির্বাচন করুন',
      'gender_female': 'মহিলা',
      'gender_male': 'পুরুষ',
      'gender_warning': 'একবার লিঙ্গ নির্বাচন করলে তা পরিবর্তন করা যাবে না! এগিয়ে যাওয়ার আগে সাবধানে বেছে নিন।',
      'select_age_range': 'বয়সের পরিসীমা নির্বাচন করুন',
      'select_age_subtitle': 'আপনার জন্য উপযুক্ত মানুষ বা কনটেন্ট খুঁজতে একটি বয়সসীমা বেছে নিন',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'বিভাগ নির্বাচন করুন',
      'select_category_subtitle': 'আপনার জন্য উপযুক্ত মানুষ বা কনটেন্ট খুঁজতে বিভাগ বেছে নিন',
      'cat_all_video': 'সব ভিডিও ডাউনলোড',
      'cat_insta': 'ইনস্টা ডাউনলোড',
      'cat_fb': 'এফবি ডাউনলোড',
      'cat_tiktok': 'টিকটক ডাউনলোড',
      'cat_twitter': 'টুইটার ডাউনলোড',
      'next_btn': 'পরবর্তী',
      'home_disclaimer': 'এই অ্যাপ কোনো কনটেন্ট হোস্ট করে না। সমস্ত ডাউনলোড সর্বজনীনভাবে শেয়ার করা লিঙ্ক থেকে।',
      'link_hint': 'এখানে ভিডিও লিঙ্ক পেস্ট করুন',
      'paste_btn': 'পেস্ট করুন',
      'download_btn': 'ডাউনলোড করুন',
      'supported_socials': 'সমর্থিত সোশ্যাল',
      'how_to_download': 'কীভাবে ডাউনলোড করবেন?',
      'downloads_title': 'ডাউনলোডস',
      'downloads_empty': 'এখনো কোনো ডাউনলোড নেই',
      'social_facebook': 'ফেসবুক',
      'social_instagram': 'ইনস্টাগ্রাম',
      'social_whatsapp': 'হোয়াটসঅ্যাপ',
      'social_pinterest': 'পিন্টারেস্ট',
      'media_photos': 'ফটো',
      'media_video': 'ভিডিও',
    },
    const Locale('zh', 'CN'): {
      'lan': '中文',
      'select_language': '选择语言',
      'perm_title': '权限',
      'perm_heading': '读写权限',
      'perm_subtitle': '此应用需要存储权限才能访问您的图片库。没有此权限，应用将无法正常运行。',
      'allow_access': '允许访问',
      'privacy_title': '隐私政策',
      'privacy_intro': '当您使用我们的应用程序时，本隐私政策说明我们收集的信息以及我们如何使用这些信息。您的隐私对我们很重要。',
      'privacy_notif_title': '通知',
      'privacy_notif_body': '此权限用于向您发送提醒和重要更新。',
      'privacy_photos_title': '照片和视频',
      'privacy_photos_body': '此权限允许应用访问您设备上的照片和视频库，以便应用正常运行。',
      'privacy_network_title': '完全网络访问',
      'privacy_network_body': '用于接收更新通知和访问应用分类标签。',
      'privacy_agree_checkbox': '我已阅读并接受隐私政策',
      'agree_next': '同意并继续',
      'onboard_title_1': 'XVX 4K 视频下载器',
      'onboard_sub_1': '从各种平台下载视频',
      'onboard_title_2': '粘贴并下载',
      'onboard_sub_2': '粘贴链接并下载视频',
      'onboard_title_3': '3倍速下载',
      'onboard_sub_3': '下载速度比平常快3倍',
      'personalized_title': '个性化信息',
      'personalized_subtitle': '获取为您量身定制的更新和内容',
      'select_gender': '选择性别',
      'gender_female': '女性',
      'gender_male': '男性',
      'gender_warning': '一旦选择性别，将无法更改！请在继续之前仔细选择。',
      'select_age_range': '选择年龄段',
      'select_age_subtitle': '选择一个年龄段以发现最适合您的人或内容',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': '选择类别',
      'select_category_subtitle': '选择类别以发现最适合您的人或内容',
      'cat_all_video': '全部视频下载',
      'cat_insta': 'Ins下载',
      'cat_fb': '脸书下载',
      'cat_tiktok': '抖音下载',
      'cat_twitter': '推特下载',
      'next_btn': '下一步',
      'home_disclaimer': '本应用不托管任何内容。所有下载均来自公开分享的链接。',
      'link_hint': '在此粘贴视频链接',
      'paste_btn': '粘贴',
      'download_btn': '下载',
      'supported_socials': '支持的社交平台',
      'how_to_download': '如何下载？',
      'downloads_title': '下载',
      'downloads_empty': '暂无下载内容',
      'social_facebook': '脸书',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'WhatsApp',
      'social_pinterest': 'Pinterest',
      'media_photos': '照片',
      'media_video': '视频',
    },
    const Locale('fr', 'FR'): {
      'lan': 'Français',
      'select_language': 'Choisir la langue',
      'perm_title': 'Autorisation',
      'perm_heading': 'Autorisation de lecture et d\'écriture',
      'perm_subtitle': 'Cette application a besoin de l\'autorisation de stockage pour accéder à votre bibliothèque d\'images. Sans cette autorisation, l\'application ne pourra pas fonctionner correctement.',
      'allow_access': 'Autoriser l\'accès',
      'privacy_title': 'Politique de confidentialité',
      'privacy_intro': 'Lorsque vous utilisez notre application, cette politique de confidentialité décrit les informations que nous collectons et comment nous les utilisons. Votre vie privée est importante pour nous.',
      'privacy_notif_title': 'Notifications',
      'privacy_notif_body': 'Cette autorisation est utilisée pour vous envoyer des rappels et des mises à jour importantes.',
      'privacy_photos_title': 'Photos et vidéos',
      'privacy_photos_body': 'Cette autorisation permet à l\'application d\'accéder à la bibliothèque de photos et vidéos de votre appareil afin qu\'elle fonctionne correctement.',
      'privacy_network_title': 'Accès réseau complet',
      'privacy_network_body': 'Utilisé pour recevoir les notifications de mise à jour et accéder aux étiquettes de classification de l\'application.',
      'privacy_agree_checkbox': 'J\'ai lu et j\'accepte la politique de confidentialité',
      'agree_next': 'Accepter et continuer',
      'onboard_title_1': 'XVX Téléchargeur de vidéo 4K',
      'onboard_sub_1': 'Téléchargez des vidéos depuis diverses plateformes',
      'onboard_title_2': 'Coller et télécharger',
      'onboard_sub_2': 'Collez un lien et téléchargez des vidéos',
      'onboard_title_3': 'Téléchargement 3x plus rapide',
      'onboard_sub_3': 'Téléchargez des vidéos 3 fois plus vite que d\'habitude',
      'personalized_title': 'Informations personnalisées',
      'personalized_subtitle': 'Recevez des mises à jour et du contenu adaptés à vous',
      'select_gender': 'Choisir le genre',
      'gender_female': 'Femme',
      'gender_male': 'Homme',
      'gender_warning': 'Une fois votre genre sélectionné, il ne peut plus être modifié ! Choisissez avec soin avant de continuer.',
      'select_age_range': 'Sélectionner la tranche d\'âge',
      'select_age_subtitle': 'Choisissez une tranche d\'âge pour découvrir des personnes ou du contenu qui vous convient',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'Sélectionner une catégorie',
      'select_category_subtitle': 'Choisissez une catégorie pour découvrir des personnes ou du contenu qui vous convient',
      'cat_all_video': 'Téléchargement de toutes les vidéos',
      'cat_insta': 'Téléchargement Insta',
      'cat_fb': 'Téléchargement FB',
      'cat_tiktok': 'Téléchargement Tik Tok',
      'cat_twitter': 'Téléchargement Twitter',
      'next_btn': 'Suivant',
      'home_disclaimer': 'Cette application n\'héberge aucun contenu. Tous les téléchargements proviennent de liens partagés publiquement.',
      'link_hint': 'Collez le lien vidéo ici',
      'paste_btn': 'Coller',
      'download_btn': 'Télécharger',
      'supported_socials': 'Réseaux pris en charge',
      'how_to_download': 'Comment télécharger ?',
      'downloads_title': 'Téléchargements',
      'downloads_empty': 'Aucun téléchargement pour l\'instant',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': 'Photos',
      'media_video': 'Vidéo',
    },
    const Locale('de', 'DE'): {
      'lan': 'Deutsch',
      'select_language': 'Sprache auswählen',
      'perm_title': 'Berechtigung',
      'perm_heading': 'Lese- und Schreibberechtigung',
      'perm_subtitle': 'Diese App benötigt Speicherzugriff, um auf Ihre Bildbibliothek zuzugreifen. Ohne diese Berechtigung kann die App nicht ordnungsgemäß funktionieren.',
      'allow_access': 'Zugriff erlauben',
      'privacy_title': 'Datenschutzrichtlinie',
      'privacy_intro': 'Wenn Sie unsere App verwenden, beschreibt diese Datenschutzrichtlinie, welche Informationen wir sammeln und wie wir sie verwenden. Ihre Privatsphäre ist uns wichtig.',
      'privacy_notif_title': 'Benachrichtigungen',
      'privacy_notif_body': 'Diese Berechtigung wird verwendet, um Ihnen Erinnerungen und wichtige Updates zu senden.',
      'privacy_photos_title': 'Fotos und Videos',
      'privacy_photos_body': 'Diese Berechtigung ermöglicht der App den Zugriff auf die Foto- und Videobibliothek Ihres Geräts, damit die App ordnungsgemäß funktioniert.',
      'privacy_network_title': 'Voller Netzwerkzugriff',
      'privacy_network_body': 'Wird verwendet, um Update-Benachrichtigungen zu erhalten und auf App-Klassifizierungslabels zuzugreifen.',
      'privacy_agree_checkbox': 'Ich habe die Datenschutzrichtlinie gelesen und akzeptiere sie',
      'agree_next': 'Zustimmen & Weiter',
      'onboard_title_1': 'XVX 4K Video-Downloader',
      'onboard_sub_1': 'Videos von verschiedenen Plattformen herunterladen',
      'onboard_title_2': 'Einfügen & Herunterladen',
      'onboard_sub_2': 'Link einfügen und Videos herunterladen',
      'onboard_title_3': '3x schnellerer Download',
      'onboard_sub_3': 'Videos 3x schneller als gewöhnlich herunterladen',
      'personalized_title': 'Personalisierte Informationen',
      'personalized_subtitle': 'Erhalten Sie Updates und Inhalte, die auf Sie zugeschnitten sind',
      'select_gender': 'Geschlecht wählen',
      'gender_female': 'Weiblich',
      'gender_male': 'Männlich',
      'gender_warning': 'Sobald Sie Ihr Geschlecht ausgewählt haben, kann es nicht mehr geändert werden! Wählen Sie sorgfältig, bevor Sie fortfahren.',
      'select_age_range': 'Altersgruppe wählen',
      'select_age_subtitle': 'Wählen Sie eine Altersgruppe, um Personen oder Inhalte zu entdecken, die zu Ihnen passen',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'Kategorie wählen',
      'select_category_subtitle': 'Wählen Sie eine Kategorie, um Personen oder Inhalte zu entdecken, die zu Ihnen passen',
      'cat_all_video': 'Alle Videos herunterladen',
      'cat_insta': 'Insta-Download',
      'cat_fb': 'FB-Download',
      'cat_tiktok': 'Tik-Tok-Download',
      'cat_twitter': 'Twitter-Download',
      'next_btn': 'Weiter',
      'home_disclaimer': 'Diese App hostet keine Inhalte. Alle Downloads stammen aus öffentlich geteilten Links.',
      'link_hint': 'Videolink hier einfügen',
      'paste_btn': 'Einfügen',
      'download_btn': 'Herunterladen',
      'supported_socials': 'Unterstützte Plattformen',
      'how_to_download': 'Wie herunterladen?',
      'downloads_title': 'Downloads',
      'downloads_empty': 'Noch keine Downloads',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': 'Fotos',
      'media_video': 'Video',
    },
    const Locale('id', 'ID'): {
      'lan': 'Bahasa Indonesia',
      'select_language': 'Pilih bahasa',
      'perm_title': 'Izin',
      'perm_heading': 'Izin Baca dan Tulis',
      'perm_subtitle': 'Aplikasi ini memerlukan izin penyimpanan untuk mengakses galeri gambar Anda. Tanpa izin ini, aplikasi tidak dapat berjalan dengan baik.',
      'allow_access': 'Izinkan Akses',
      'privacy_title': 'Kebijakan Privasi',
      'privacy_intro': 'Saat Anda menggunakan aplikasi kami, Kebijakan Privasi ini menjelaskan informasi yang kami kumpulkan dan cara kami menggunakannya. Privasi Anda penting bagi kami.',
      'privacy_notif_title': 'Notifikasi',
      'privacy_notif_body': 'Izin ini digunakan untuk mengirimkan pengingat dan pembaruan penting kepada Anda.',
      'privacy_photos_title': 'Foto dan Video',
      'privacy_photos_body': 'Izin ini memungkinkan aplikasi mengakses galeri foto dan video perangkat Anda agar aplikasi dapat berjalan dengan baik.',
      'privacy_network_title': 'Akses jaringan penuh',
      'privacy_network_body': 'Digunakan untuk menerima notifikasi pembaruan dan mengakses label klasifikasi aplikasi.',
      'privacy_agree_checkbox': 'Saya telah membaca dan menyetujui kebijakan privasi',
      'agree_next': 'Setuju & Lanjut',
      'onboard_title_1': 'XVX Pengunduh Video 4K',
      'onboard_sub_1': 'Unduh video dari berbagai platform',
      'onboard_title_2': 'Tempel & Unduh',
      'onboard_sub_2': 'Tempel tautan dan unduh video',
      'onboard_title_3': 'Unduhan 3x Lebih Cepat',
      'onboard_sub_3': 'Unduh video 3x lebih cepat dari biasanya',
      'personalized_title': 'Informasi Personal',
      'personalized_subtitle': 'Dapatkan pembaruan dan konten yang disesuaikan untuk Anda',
      'select_gender': 'Pilih Jenis Kelamin',
      'gender_female': 'Perempuan',
      'gender_male': 'Laki-laki',
      'gender_warning': 'Setelah Anda memilih jenis kelamin, tidak dapat diubah! Pastikan untuk memilih dengan hati-hati sebelum melanjutkan.',
      'select_age_range': 'Pilih Rentang Usia',
      'select_age_subtitle': 'Pilih rentang usia untuk menemukan orang atau konten yang paling sesuai untuk Anda',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'Pilih Kategori',
      'select_category_subtitle': 'Pilih kategori untuk menemukan orang atau konten yang paling sesuai untuk Anda',
      'cat_all_video': 'Unduh Semua Video',
      'cat_insta': 'Unduh Insta',
      'cat_fb': 'Unduh FB',
      'cat_tiktok': 'Unduh Tik Tok',
      'cat_twitter': 'Unduh Twitter',
      'next_btn': 'Lanjut',
      'home_disclaimer': 'Aplikasi ini tidak menghosting konten apa pun. Semua unduhan berasal dari tautan yang dibagikan secara publik.',
      'link_hint': 'Tempel tautan video di sini',
      'paste_btn': 'Tempel',
      'download_btn': 'Unduh',
      'supported_socials': 'Sosial yang Didukung',
      'how_to_download': 'Cara Mengunduh?',
      'downloads_title': 'Unduhan',
      'downloads_empty': 'Belum ada unduhan',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': 'Foto',
      'media_video': 'Video',
    },
    const Locale('it', 'IT'): {
      'lan': 'Italiano',
      'select_language': 'Seleziona lingua',
      'perm_title': 'Autorizzazione',
      'perm_heading': 'Autorizzazione di lettura e scrittura',
      'perm_subtitle': 'Questa app necessita dell\'autorizzazione di archiviazione per accedere alla libreria immagini. Senza questa autorizzazione l\'app non potrà funzionare correttamente.',
      'allow_access': 'Consenti accesso',
      'privacy_title': 'Informativa sulla privacy',
      'privacy_intro': 'Quando utilizzi la nostra applicazione, questa informativa sulla privacy descrive le informazioni che raccogliamo e come le utilizziamo. La tua privacy è importante per noi.',
      'privacy_notif_title': 'Notifiche',
      'privacy_notif_body': 'Questa autorizzazione viene utilizzata per inviarti promemoria e aggiornamenti importanti.',
      'privacy_photos_title': 'Foto e video',
      'privacy_photos_body': 'Questa autorizzazione consente all\'app di accedere alla libreria di foto e video del tuo dispositivo affinché funzioni correttamente.',
      'privacy_network_title': 'Accesso completo alla rete',
      'privacy_network_body': 'Utilizzato per ricevere notifiche di aggiornamento e accedere alle etichette di classificazione dell\'app.',
      'privacy_agree_checkbox': 'Ho letto e accetto l\'informativa sulla privacy',
      'agree_next': 'Accetta e continua',
      'onboard_title_1': 'XVX Downloader Video 4K',
      'onboard_sub_1': 'Scarica video da varie piattaforme',
      'onboard_title_2': 'Incolla e Scarica',
      'onboard_sub_2': 'Incolla un link e scarica i video',
      'onboard_title_3': 'Download 3 volte più veloce',
      'onboard_sub_3': 'Scarica i video 3 volte più velocemente del solito',
      'personalized_title': 'Informazioni personalizzate',
      'personalized_subtitle': 'Ricevi aggiornamenti e contenuti su misura per te',
      'select_gender': 'Seleziona genere',
      'gender_female': 'Femmina',
      'gender_male': 'Maschio',
      'gender_warning': 'Una volta selezionato il genere, non potrà essere modificato! Scegli con attenzione prima di procedere.',
      'select_age_range': 'Seleziona fascia d\'età',
      'select_age_subtitle': 'Scegli una fascia d\'età per scoprire persone o contenuti più adatti a te',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'Seleziona categoria',
      'select_category_subtitle': 'Scegli una categoria per scoprire persone o contenuti più adatti a te',
      'cat_all_video': 'Scarica tutti i video',
      'cat_insta': 'Scarica Insta',
      'cat_fb': 'Scarica FB',
      'cat_tiktok': 'Scarica Tik Tok',
      'cat_twitter': 'Scarica Twitter',
      'next_btn': 'Avanti',
      'home_disclaimer': 'Questa app non ospita alcun contenuto. Tutti i download provengono da link condivisi pubblicamente.',
      'link_hint': 'Incolla qui il link del video',
      'paste_btn': 'Incolla',
      'download_btn': 'Scarica',
      'supported_socials': 'Social supportati',
      'how_to_download': 'Come scaricare?',
      'downloads_title': 'Download',
      'downloads_empty': 'Nessun download ancora',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': 'Foto',
      'media_video': 'Video',
    },
    const Locale('ja', 'JP'): {
      'lan': '日本語',
      'select_language': '言語を選択',
      'perm_title': '権限',
      'perm_heading': '読み書きの権限',
      'perm_subtitle': 'このアプリが画像ライブラリにアクセスするにはストレージの権限が必要です。この権限がないとアプリが正常に動作しません。',
      'allow_access': 'アクセスを許可',
      'privacy_title': 'プライバシーポリシー',
      'privacy_intro': '当アプリをご利用の際、このプライバシーポリシーは当社が収集する情報とその使用方法について説明します。お客様のプライバシーは私たちにとって重要です。',
      'privacy_notif_title': '通知',
      'privacy_notif_body': 'この権限はリマインダーや重要な更新情報を送信するために使用されます。',
      'privacy_photos_title': '写真と動画',
      'privacy_photos_body': 'この権限により、アプリが正常に動作するようデバイスの写真と動画ライブラリにアクセスできます。',
      'privacy_network_title': '完全なネットワークアクセス',
      'privacy_network_body': '更新通知の受信やアプリ分類ラベルへのアクセスに使用されます。',
      'privacy_agree_checkbox': 'プライバシーポリシーを読み、同意しました',
      'agree_next': '同意して次へ',
      'onboard_title_1': 'XVX 4K動画ダウンローダー',
      'onboard_sub_1': '様々なプラットフォームから動画をダウンロード',
      'onboard_title_2': '貼り付けてダウンロード',
      'onboard_sub_2': 'リンクを貼り付けて動画をダウンロード',
      'onboard_title_3': '3倍速いダウンロード',
      'onboard_sub_3': '通常より3倍速く動画をダウンロード',
      'personalized_title': 'パーソナライズされた情報',
      'personalized_subtitle': 'あなたに合わせた更新情報やコンテンツを取得',
      'select_gender': '性別を選択',
      'gender_female': '女性',
      'gender_male': '男性',
      'gender_warning': '性別は一度選択すると変更できません！続行する前によく確認してください。',
      'select_age_range': '年齢層を選択',
      'select_age_subtitle': 'あなたに最適な人やコンテンツを見つけるために年齢層を選んでください',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'カテゴリを選択',
      'select_category_subtitle': 'あなたに最適な人やコンテンツを見つけるためにカテゴリを選んでください',
      'cat_all_video': 'すべての動画をダウンロード',
      'cat_insta': 'Insta ダウンロード',
      'cat_fb': 'FB ダウンロード',
      'cat_tiktok': 'Tik Tok ダウンロード',
      'cat_twitter': 'Twitter ダウンロード',
      'next_btn': '次へ',
      'home_disclaimer': 'このアプリはコンテンツをホストしません。すべてのダウンロードは公開共有されたリンクからです。',
      'link_hint': 'ここに動画リンクを貼り付け',
      'paste_btn': '貼り付け',
      'download_btn': 'ダウンロード',
      'supported_socials': '対応SNS',
      'how_to_download': 'ダウンロード方法は？',
      'downloads_title': 'ダウンロード',
      'downloads_empty': 'まだダウンロードがありません',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': '写真',
      'media_video': '動画',
    },
    const Locale('ko', 'KR'): {
      'lan': '한국어',
      'select_language': '언어 선택',
      'perm_title': '권한',
      'perm_heading': '읽기 및 쓰기 권한',
      'perm_subtitle': '이 앱이 이미지 라이브러리에 접근하려면 저장소 권한이 필요합니다. 이 권한이 없으면 앱이 제대로 작동하지 않습니다.',
      'allow_access': '액세스 허용',
      'privacy_title': '개인정보 처리방침',
      'privacy_intro': '앱을 사용하실 때, 이 개인정보 처리방침은 저희가 수집하는 정보와 그 사용 방법을 설명합니다. 고객님의 개인정보는 저희에게 중요합니다.',
      'privacy_notif_title': '알림',
      'privacy_notif_body': '이 권한은 알림 및 중요 업데이트를 보내는 데 사용됩니다.',
      'privacy_photos_title': '사진 및 동영상',
      'privacy_photos_body': '이 권한을 통해 앱이 정상적으로 작동하도록 기기의 사진 및 동영상 라이브러리에 접근할 수 있습니다.',
      'privacy_network_title': '전체 네트워크 접근',
      'privacy_network_body': '업데이트 알림 수신 및 앱 분류 라벨 접근에 사용됩니다.',
      'privacy_agree_checkbox': '개인정보 처리방침을 읽고 동의합니다',
      'agree_next': '동의 및 계속',
      'onboard_title_1': 'XVX 4K 동영상 다운로더',
      'onboard_sub_1': '다양한 플랫폼에서 동영상 다운로드',
      'onboard_title_2': '붙여넣기 & 다운로드',
      'onboard_sub_2': '링크를 붙여넣고 동영상을 다운로드하세요',
      'onboard_title_3': '3배 빠른 다운로드',
      'onboard_sub_3': '평소보다 3배 빠르게 동영상 다운로드',
      'personalized_title': '맞춤 정보',
      'personalized_subtitle': '당신을 위한 맞춤 업데이트와 콘텐츠를 받아보세요',
      'select_gender': '성별 선택',
      'gender_female': '여성',
      'gender_male': '남성',
      'gender_warning': '성별을 선택하면 변경할 수 없습니다! 진행하기 전에 신중히 선택하세요.',
      'select_age_range': '연령대 선택',
      'select_age_subtitle': '가장 적합한 사람이나 콘텐츠를 찾기 위해 연령대를 선택하세요',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': '카테고리 선택',
      'select_category_subtitle': '가장 적합한 사람이나 콘텐츠를 찾기 위해 카테고리를 선택하세요',
      'cat_all_video': '모든 동영상 다운로드',
      'cat_insta': '인스타 다운로드',
      'cat_fb': '페이스북 다운로드',
      'cat_tiktok': '틱톡 다운로드',
      'cat_twitter': '트위터 다운로드',
      'next_btn': '다음',
      'home_disclaimer': '이 앱은 콘텐츠를 호스팅하지 않습니다. 모든 다운로드는 공개적으로 공유된 링크에서 제공됩니다.',
      'link_hint': '여기에 동영상 링크 붙여넣기',
      'paste_btn': '붙여넣기',
      'download_btn': '다운로드',
      'supported_socials': '지원하는 소셜',
      'how_to_download': '다운로드 방법?',
      'downloads_title': '다운로드',
      'downloads_empty': '아직 다운로드 없음',
      'social_facebook': '페이스북',
      'social_instagram': '인스타그램',
      'social_whatsapp': '왓츠앱',
      'social_pinterest': '핀터레스트',
      'media_photos': '사진',
      'media_video': '동영상',
    },
    const Locale('pl', 'PL'): {
      'lan': 'Polski',
      'select_language': 'Wybierz język',
      'perm_title': 'Uprawnienie',
      'perm_heading': 'Uprawnienie do odczytu i zapisu',
      'perm_subtitle': 'Ta aplikacja potrzebuje uprawnienia do pamięci, aby uzyskać dostęp do biblioteki obrazów. Bez tego uprawnienia aplikacja nie będzie działać poprawnie.',
      'allow_access': 'Zezwól na dostęp',
      'privacy_title': 'Polityka prywatności',
      'privacy_intro': 'Podczas korzystania z naszej aplikacji ta polityka prywatności opisuje, jakie informacje zbieramy i jak ich używamy. Twoja prywatność jest dla nas ważna.',
      'privacy_notif_title': 'Powiadomienia',
      'privacy_notif_body': 'To uprawnienie służy do wysyłania przypomnień i ważnych aktualizacji.',
      'privacy_photos_title': 'Zdjęcia i filmy',
      'privacy_photos_body': 'To uprawnienie pozwala aplikacji uzyskać dostęp do biblioteki zdjęć i filmów urządzenia, aby aplikacja działała poprawnie.',
      'privacy_network_title': 'Pełny dostęp do sieci',
      'privacy_network_body': 'Używane do otrzymywania powiadomień o aktualizacjach i dostępu do etykiet klasyfikacji aplikacji.',
      'privacy_agree_checkbox': 'Przeczytałem i akceptuję politykę prywatności',
      'agree_next': 'Zgadzam się i dalej',
      'onboard_title_1': 'XVX Pobieranie wideo 4K',
      'onboard_sub_1': 'Pobieraj filmy z różnych platform',
      'onboard_title_2': 'Wklej i pobierz',
      'onboard_sub_2': 'Wklej link i pobierz filmy',
      'onboard_title_3': '3x szybsze pobieranie',
      'onboard_sub_3': 'Pobieraj filmy 3 razy szybciej niż zwykle',
      'personalized_title': 'Spersonalizowane informacje',
      'personalized_subtitle': 'Otrzymuj aktualizacje i treści dopasowane do Ciebie',
      'select_gender': 'Wybierz płeć',
      'gender_female': 'Kobieta',
      'gender_male': 'Mężczyzna',
      'gender_warning': 'Po wybraniu płci nie będzie można jej zmienić! Wybierz uważnie przed kontynuowaniem.',
      'select_age_range': 'Wybierz przedział wiekowy',
      'select_age_subtitle': 'Wybierz przedział wiekowy, aby odkryć osoby lub treści dopasowane do Ciebie',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'Wybierz kategorię',
      'select_category_subtitle': 'Wybierz kategorię, aby odkryć osoby lub treści dopasowane do Ciebie',
      'cat_all_video': 'Pobierz wszystkie filmy',
      'cat_insta': 'Pobieranie z Insta',
      'cat_fb': 'Pobieranie z FB',
      'cat_tiktok': 'Pobieranie z Tik Tok',
      'cat_twitter': 'Pobieranie z Twitter',
      'next_btn': 'Dalej',
      'home_disclaimer': 'Ta aplikacja nie hostuje żadnych treści. Wszystkie pobrania pochodzą z publicznie udostępnionych linków.',
      'link_hint': 'Wklej tutaj link do wideo',
      'paste_btn': 'Wklej',
      'download_btn': 'Pobierz',
      'supported_socials': 'Obsługiwane platformy',
      'how_to_download': 'Jak pobrać?',
      'downloads_title': 'Pobrane',
      'downloads_empty': 'Brak pobrań',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': 'Zdjęcia',
      'media_video': 'Wideo',
    },
    const Locale('pt', 'PT'): {
      'lan': 'Português',
      'select_language': 'Selecionar idioma',
      'perm_title': 'Permissão',
      'perm_heading': 'Permissão de leitura e escrita',
      'perm_subtitle': 'Este aplicativo precisa de permissão de armazenamento para acessar sua biblioteca de imagens. Sem esta permissão, o aplicativo não funcionará corretamente.',
      'allow_access': 'Permitir acesso',
      'privacy_title': 'Política de privacidade',
      'privacy_intro': 'Ao usar nosso aplicativo, esta política de privacidade descreve as informações que coletamos e como as usamos. Sua privacidade é importante para nós.',
      'privacy_notif_title': 'Notificações',
      'privacy_notif_body': 'Esta permissão é usada para enviar lembretes e atualizações importantes.',
      'privacy_photos_title': 'Fotos e vídeos',
      'privacy_photos_body': 'Esta permissão permite que o aplicativo acesse a biblioteca de fotos e vídeos do seu dispositivo para que funcione corretamente.',
      'privacy_network_title': 'Acesso total à rede',
      'privacy_network_body': 'Usado para receber notificações de atualização e acessar rótulos de classificação do aplicativo.',
      'privacy_agree_checkbox': 'Li e aceito a política de privacidade',
      'agree_next': 'Concordar e continuar',
      'onboard_title_1': 'XVX Downloader de vídeo 4K',
      'onboard_sub_1': 'Baixe vídeos de várias plataformas',
      'onboard_title_2': 'Colar e baixar',
      'onboard_sub_2': 'Cole um link e baixe vídeos',
      'onboard_title_3': 'Download 3x mais rápido',
      'onboard_sub_3': 'Baixe vídeos 3 vezes mais rápido que o normal',
      'personalized_title': 'Informações personalizadas',
      'personalized_subtitle': 'Receba atualizações e conteúdo feitos para você',
      'select_gender': 'Selecionar gênero',
      'gender_female': 'Feminino',
      'gender_male': 'Masculino',
      'gender_warning': 'Depois de selecionar seu gênero, ele não poderá ser alterado! Escolha com cuidado antes de prosseguir.',
      'select_age_range': 'Selecionar faixa etária',
      'select_age_subtitle': 'Escolha uma faixa etária para descobrir pessoas ou conteúdo que combinam com você',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'Selecionar categoria',
      'select_category_subtitle': 'Escolha uma categoria para descobrir pessoas ou conteúdo que combinam com você',
      'cat_all_video': 'Baixar todos os vídeos',
      'cat_insta': 'Baixar do Insta',
      'cat_fb': 'Baixar do FB',
      'cat_tiktok': 'Baixar do Tik Tok',
      'cat_twitter': 'Baixar do Twitter',
      'next_btn': 'Próximo',
      'home_disclaimer': 'Este aplicativo não hospeda nenhum conteúdo. Todos os downloads são de links compartilhados publicamente.',
      'link_hint': 'Cole o link do vídeo aqui',
      'paste_btn': 'Colar',
      'download_btn': 'Baixar',
      'supported_socials': 'Redes suportadas',
      'how_to_download': 'Como baixar?',
      'downloads_title': 'Downloads',
      'downloads_empty': 'Nenhum download ainda',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': 'Fotos',
      'media_video': 'Vídeo',
    },
    const Locale('ro', 'RO'): {
      'lan': 'Română',
      'select_language': 'Selectează limba',
      'perm_title': 'Permisiune',
      'perm_heading': 'Permisiune de citire și scriere',
      'perm_subtitle': 'Această aplicație are nevoie de permisiunea de stocare pentru a accesa biblioteca de imagini. Fără această permisiune, aplicația nu va funcționa corect.',
      'allow_access': 'Permite accesul',
      'privacy_title': 'Politica de confidențialitate',
      'privacy_intro': 'Când folosiți aplicația noastră, această politică de confidențialitate descrie informațiile pe care le colectăm și modul în care le folosim. Confidențialitatea dumneavoastră este importantă pentru noi.',
      'privacy_notif_title': 'Notificări',
      'privacy_notif_body': 'Această permisiune este folosită pentru a vă trimite memento-uri și actualizări importante.',
      'privacy_photos_title': 'Fotografii și videoclipuri',
      'privacy_photos_body': 'Această permisiune permite aplicației să acceseze biblioteca de fotografii și videoclipuri a dispozitivului pentru ca aplicația să funcționeze corect.',
      'privacy_network_title': 'Acces complet la rețea',
      'privacy_network_body': 'Folosit pentru a primi notificări de actualizare și pentru a accesa etichetele de clasificare a aplicației.',
      'privacy_agree_checkbox': 'Am citit și accept politica de confidențialitate',
      'agree_next': 'Accept și continuă',
      'onboard_title_1': 'XVX Descărcător video 4K',
      'onboard_sub_1': 'Descarcă videoclipuri de pe diverse platforme',
      'onboard_title_2': 'Lipește și descarcă',
      'onboard_sub_2': 'Lipește un link și descarcă videoclipuri',
      'onboard_title_3': 'Descărcare de 3 ori mai rapidă',
      'onboard_sub_3': 'Descarcă videoclipuri de 3 ori mai repede ca de obicei',
      'personalized_title': 'Informații personalizate',
      'personalized_subtitle': 'Primește actualizări și conținut adaptate pentru tine',
      'select_gender': 'Selectează genul',
      'gender_female': 'Femeie',
      'gender_male': 'Bărbat',
      'gender_warning': 'Odată selectat, genul nu mai poate fi schimbat! Alegeți cu grijă înainte de a continua.',
      'select_age_range': 'Selectează intervalul de vârstă',
      'select_age_subtitle': 'Alege un interval de vârstă pentru a descoperi persoane sau conținut potrivit pentru tine',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'Selectează categoria',
      'select_category_subtitle': 'Alege o categorie pentru a descoperi persoane sau conținut potrivit pentru tine',
      'cat_all_video': 'Descarcă toate videoclipurile',
      'cat_insta': 'Descărcare Insta',
      'cat_fb': 'Descărcare FB',
      'cat_tiktok': 'Descărcare Tik Tok',
      'cat_twitter': 'Descărcare Twitter',
      'next_btn': 'Următorul',
      'home_disclaimer': 'Această aplicație nu găzduiește conținut. Toate descărcările provin din linkuri distribuite public.',
      'link_hint': 'Lipiți linkul video aici',
      'paste_btn': 'Lipește',
      'download_btn': 'Descarcă',
      'supported_socials': 'Rețele acceptate',
      'how_to_download': 'Cum se descarcă?',
      'downloads_title': 'Descărcări',
      'downloads_empty': 'Nicio descărcare încă',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': 'Fotografii',
      'media_video': 'Video',
    },
    const Locale('es', 'ES'): {
      'lan': 'Español',
      'select_language': 'Seleccionar idioma',
      'perm_title': 'Permiso',
      'perm_heading': 'Permiso de lectura y escritura',
      'perm_subtitle': 'Esta aplicación necesita permiso de almacenamiento para acceder a tu biblioteca de imágenes. Sin este permiso, la aplicación no podrá funcionar correctamente.',
      'allow_access': 'Permitir acceso',
      'privacy_title': 'Política de privacidad',
      'privacy_intro': 'Cuando usas nuestra aplicación, esta política de privacidad describe la información que recopilamos y cómo la usamos. Tu privacidad es importante para nosotros.',
      'privacy_notif_title': 'Notificaciones',
      'privacy_notif_body': 'Este permiso se usa para enviarte recordatorios y actualizaciones importantes.',
      'privacy_photos_title': 'Fotos y videos',
      'privacy_photos_body': 'Este permiso permite que la app acceda a la biblioteca de fotos y videos de tu dispositivo para que funcione correctamente.',
      'privacy_network_title': 'Acceso completo a la red',
      'privacy_network_body': 'Se usa para recibir notificaciones de actualización y acceder a etiquetas de clasificación de la app.',
      'privacy_agree_checkbox': 'He leído y acepto la política de privacidad',
      'agree_next': 'Aceptar y continuar',
      'onboard_title_1': 'XVX Descargador de video 4K',
      'onboard_sub_1': 'Descarga videos de varias plataformas',
      'onboard_title_2': 'Pegar y descargar',
      'onboard_sub_2': 'Pega un enlace y descarga videos',
      'onboard_title_3': 'Descarga 3 veces más rápida',
      'onboard_sub_3': 'Descarga videos 3 veces más rápido de lo normal',
      'personalized_title': 'Información personalizada',
      'personalized_subtitle': 'Recibe actualizaciones y contenido hecho para ti',
      'select_gender': 'Seleccionar género',
      'gender_female': 'Mujer',
      'gender_male': 'Hombre',
      'gender_warning': 'Una vez que selecciones tu género, no podrá cambiarse. Asegúrate de elegir con cuidado antes de continuar.',
      'select_age_range': 'Seleccionar rango de edad',
      'select_age_subtitle': 'Elige un rango de edad para descubrir personas o contenido que se ajuste a ti',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'Seleccionar categoría',
      'select_category_subtitle': 'Elige una categoría para descubrir personas o contenido que se ajuste a ti',
      'cat_all_video': 'Descargar todos los videos',
      'cat_insta': 'Descarga de Insta',
      'cat_fb': 'Descarga de FB',
      'cat_tiktok': 'Descarga de Tik Tok',
      'cat_twitter': 'Descarga de Twitter',
      'next_btn': 'Siguiente',
      'home_disclaimer': 'Esta aplicación no aloja ningún contenido. Todas las descargas provienen de enlaces compartidos públicamente.',
      'link_hint': 'Pega el enlace del video aquí',
      'paste_btn': 'Pegar',
      'download_btn': 'Descargar',
      'supported_socials': 'Redes compatibles',
      'how_to_download': '¿Cómo descargar?',
      'downloads_title': 'Descargas',
      'downloads_empty': 'Aún no hay descargas',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': 'Fotos',
      'media_video': 'Video',
    },
    const Locale('sw', 'KE'): {
      'lan': 'Kiswahili',
      'select_language': 'Chagua lugha',
      'perm_title': 'Ruhusa',
      'perm_heading': 'Ruhusa ya Kusoma na Kuandika',
      'perm_subtitle': 'Programu hii inahitaji ruhusa ya hifadhi ili kufikia maktaba yako ya picha. Bila ruhusa hii, programu haitaweza kufanya kazi vizuri.',
      'allow_access': 'Ruhusu Ufikiaji',
      'privacy_title': 'Sera ya Faragha',
      'privacy_intro': 'Unapotumia programu yetu, sera hii ya faragha inaelezea taarifa tunazokusanya na jinsi tunavyozitumia. Faragha yako ni muhimu kwetu.',
      'privacy_notif_title': 'Arifa',
      'privacy_notif_body': 'Ruhusa hii hutumika kukutumia vikumbusho na masasisho muhimu.',
      'privacy_photos_title': 'Picha na Video',
      'privacy_photos_body': 'Ruhusa hii huruhusu programu kufikia maktaba ya picha na video ya kifaa chako ili programu ifanye kazi vizuri.',
      'privacy_network_title': 'Ufikiaji kamili wa mtandao',
      'privacy_network_body': 'Hutumika kupokea arifa za masasisho na kufikia lebo za uainishaji wa programu.',
      'privacy_agree_checkbox': 'Nimesoma na kukubali sera ya faragha',
      'agree_next': 'Kubali na Endelea',
      'onboard_title_1': 'XVX Kipakua Video cha 4K',
      'onboard_sub_1': 'Pakua video kutoka majukwaa mbalimbali',
      'onboard_title_2': 'Bandika na Pakua',
      'onboard_sub_2': 'Bandika kiungo na pakua video',
      'onboard_title_3': 'Upakuaji wa Kasi Mara 3',
      'onboard_sub_3': 'Pakua video kwa kasi mara 3 zaidi ya kawaida',
      'personalized_title': 'Taarifa Binafsi',
      'personalized_subtitle': 'Pata masasisho na maudhui yaliyokusudiwa kwako',
      'select_gender': 'Chagua Jinsia',
      'gender_female': 'Mwanamke',
      'gender_male': 'Mwanaume',
      'gender_warning': 'Ukishachagua jinsia yako, haiwezi kubadilishwa! Hakikisha unachagua kwa makini kabla ya kuendelea.',
      'select_age_range': 'Chagua Kipimo cha Umri',
      'select_age_subtitle': 'Chagua kipimo cha umri ili kugundua watu au maudhui yanayokufaa zaidi',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'Chagua Kategoria',
      'select_category_subtitle': 'Chagua kategoria ili kugundua watu au maudhui yanayokufaa zaidi',
      'cat_all_video': 'Pakua Video Zote',
      'cat_insta': 'Upakuaji wa Insta',
      'cat_fb': 'Upakuaji wa FB',
      'cat_tiktok': 'Upakuaji wa Tik Tok',
      'cat_twitter': 'Upakuaji wa Twitter',
      'next_btn': 'Endelea',
      'home_disclaimer': 'Programu hii haihifadhi maudhui yoyote. Vipakuliwa vyote vinatoka kwa viungo vilivyoshirikiwa hadharani.',
      'link_hint': 'Bandika kiungo cha video hapa',
      'paste_btn': 'Bandika',
      'download_btn': 'Pakua',
      'supported_socials': 'Mitandao Inayotumika',
      'how_to_download': 'Jinsi ya Kupakua?',
      'downloads_title': 'Vipakuliwa',
      'downloads_empty': 'Bado hakuna vilivyopakuliwa',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': 'Picha',
      'media_video': 'Video',
    },
    const Locale('th', 'TH'): {
      'lan': 'ไทย',
      'select_language': 'เลือกภาษา',
      'perm_title': 'การอนุญาต',
      'perm_heading': 'สิทธิ์อ่านและเขียน',
      'perm_subtitle': 'แอปนี้ต้องการสิทธิ์การจัดเก็บข้อมูลเพื่อเข้าถึงคลังภาพของคุณ หากไม่มีสิทธิ์นี้ แอปจะไม่สามารถทำงานได้อย่างถูกต้อง',
      'allow_access': 'อนุญาตการเข้าถึง',
      'privacy_title': 'นโยบายความเป็นส่วนตัว',
      'privacy_intro': 'เมื่อคุณใช้แอปของเรา นโยบายความเป็นส่วนตัวนี้อธิบายข้อมูลที่เราเก็บรวบรวมและวิธีที่เราใช้ข้อมูลนั้น ความเป็นส่วนตัวของคุณสำคัญสำหรับเรา',
      'privacy_notif_title': 'การแจ้งเตือน',
      'privacy_notif_body': 'สิทธิ์นี้ใช้เพื่อส่งการแจ้งเตือนและการอัปเดตที่สำคัญให้คุณ',
      'privacy_photos_title': 'รูปภาพและวิดีโอ',
      'privacy_photos_body': 'สิทธิ์นี้อนุญาตให้แอปเข้าถึงคลังรูปภาพและวิดีโอของอุปกรณ์คุณเพื่อให้แอปทำงานได้อย่างถูกต้อง',
      'privacy_network_title': 'การเข้าถึงเครือข่ายเต็มรูปแบบ',
      'privacy_network_body': 'ใช้เพื่อรับการแจ้งเตือนการอัปเดตและเข้าถึงป้ายกำกับการจัดหมวดหมู่แอป',
      'privacy_agree_checkbox': 'ฉันได้อ่านและยอมรับนโยบายความเป็นส่วนตัวแล้ว',
      'agree_next': 'ยอมรับและดำเนินการต่อ',
      'onboard_title_1': 'XVX โปรแกรมดาวน์โหลดวิดีโอ 4K',
      'onboard_sub_1': 'ดาวน์โหลดวิดีโอจากหลากหลายแพลตฟอร์ม',
      'onboard_title_2': 'วางลิงก์และดาวน์โหลด',
      'onboard_sub_2': 'วางลิงก์แล้วดาวน์โหลดวิดีโอ',
      'onboard_title_3': 'ดาวน์โหลดเร็วขึ้น 3 เท่า',
      'onboard_sub_3': 'ดาวน์โหลดวิดีโอเร็วกว่าปกติ 3 เท่า',
      'personalized_title': 'ข้อมูลเฉพาะบุคคล',
      'personalized_subtitle': 'รับการอัปเดตและเนื้อหาที่ปรับให้เหมาะกับคุณ',
      'select_gender': 'เลือกเพศ',
      'gender_female': 'หญิง',
      'gender_male': 'ชาย',
      'gender_warning': 'เมื่อคุณเลือกเพศแล้วจะไม่สามารถเปลี่ยนได้! โปรดเลือกอย่างรอบคอบก่อนดำเนินการต่อ',
      'select_age_range': 'เลือกช่วงอายุ',
      'select_age_subtitle': 'เลือกช่วงอายุเพื่อค้นพบผู้คนหรือเนื้อหาที่เหมาะกับคุณที่สุด',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'เลือกหมวดหมู่',
      'select_category_subtitle': 'เลือกหมวดหมู่เพื่อค้นพบผู้คนหรือเนื้อหาที่เหมาะกับคุณที่สุด',
      'cat_all_video': 'ดาวน์โหลดวิดีโอทั้งหมด',
      'cat_insta': 'ดาวน์โหลด Insta',
      'cat_fb': 'ดาวน์โหลด FB',
      'cat_tiktok': 'ดาวน์โหลด Tik Tok',
      'cat_twitter': 'ดาวน์โหลด Twitter',
      'next_btn': 'ถัดไป',
      'home_disclaimer': 'แอปนี้ไม่ได้โฮสต์เนื้อหาใดๆ การดาวน์โหลดทั้งหมดมาจากลิงก์ที่แชร์แบบสาธารณะ',
      'link_hint': 'วางลิงก์วิดีโอที่นี่',
      'paste_btn': 'วาง',
      'download_btn': 'ดาวน์โหลด',
      'supported_socials': 'โซเชียลที่รองรับ',
      'how_to_download': 'ดาวน์โหลดอย่างไร?',
      'downloads_title': 'การดาวน์โหลด',
      'downloads_empty': 'ยังไม่มีการดาวน์โหลด',
      'social_facebook': 'เฟซบุ๊ก',
      'social_instagram': 'อินสตาแกรม',
      'social_whatsapp': 'วอทส์แอป',
      'social_pinterest': 'พินเทอเรสต์',
      'media_photos': 'รูปภาพ',
      'media_video': 'วิดีโอ',
    },
    const Locale('ur', 'PK'): {
      'lan': 'اردو',
      'select_language': 'زبان منتخب کریں',
      'perm_title': 'اجازت',
      'perm_heading': 'پڑھنے اور لکھنے کی اجازت',
      'perm_subtitle': 'اس ایپ کو آپ کی امیج لائبریری تک رسائی کے لیے اسٹوریج کی اجازت درکار ہے۔ اس اجازت کے بغیر ایپ صحیح طریقے سے کام نہیں کرے گی۔',
      'allow_access': 'رسائی کی اجازت دیں',
      'privacy_title': 'پرائیویسی پالیسی',
      'privacy_intro': 'جب آپ ہماری ایپ استعمال کرتے ہیں، یہ پرائیویسی پالیسی بتاتی ہے کہ ہم کون سی معلومات اکٹھی کرتے ہیں اور انہیں کیسے استعمال کرتے ہیں۔ آپ کی پرائیویسی ہمارے لیے اہم ہے۔',
      'privacy_notif_title': 'اطلاعات',
      'privacy_notif_body': 'یہ اجازت آپ کو یاد دہانیاں اور اہم اپڈیٹس بھیجنے کے لیے استعمال ہوتی ہے۔',
      'privacy_photos_title': 'تصاویر اور ویڈیوز',
      'privacy_photos_body': 'یہ اجازت ایپ کو آپ کے ڈیوائس کی تصاویر اور ویڈیو لائبریری تک رسائی دیتی ہے تاکہ ایپ صحیح طریقے سے چل سکے۔',
      'privacy_network_title': 'مکمل نیٹ ورک تک رسائی',
      'privacy_network_body': 'اپڈیٹ اطلاعات وصول کرنے اور ایپ کی درجہ بندی کے لیبلز تک رسائی کے لیے استعمال ہوتی ہے۔',
      'privacy_agree_checkbox': 'میں نے پرائیویسی پالیسی پڑھ لی ہے اور قبول کرتا ہوں',
      'agree_next': 'منظور کریں اور آگے بڑھیں',
      'onboard_title_1': 'XVX 4K ویڈیو ڈاؤن لوڈر',
      'onboard_sub_1': 'مختلف پلیٹ فارمز سے ویڈیوز ڈاؤن لوڈ کریں',
      'onboard_title_2': 'پیسٹ کریں اور ڈاؤن لوڈ کریں',
      'onboard_sub_2': 'لنک پیسٹ کریں اور ویڈیوز ڈاؤن لوڈ کریں',
      'onboard_title_3': '3 گنا تیز ڈاؤن لوڈ',
      'onboard_sub_3': 'معمول سے 3 گنا تیز ویڈیوز ڈاؤن لوڈ کریں',
      'personalized_title': 'ذاتی معلومات',
      'personalized_subtitle': 'اپنے لیے خاص اپڈیٹس اور مواد حاصل کریں',
      'select_gender': 'جنس منتخب کریں',
      'gender_female': 'خاتون',
      'gender_male': 'مرد',
      'gender_warning': 'ایک بار جنس منتخب کرنے کے بعد اسے تبدیل نہیں کیا جا سکتا! آگے بڑھنے سے پہلے احتیاط سے انتخاب کریں۔',
      'select_age_range': 'عمر کی حد منتخب کریں',
      'select_age_subtitle': 'اپنے لیے موزوں افراد یا مواد دریافت کرنے کے لیے عمر کی حد منتخب کریں',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'کیٹیگری منتخب کریں',
      'select_category_subtitle': 'اپنے لیے موزوں افراد یا مواد دریافت کرنے کے لیے کیٹیگری منتخب کریں',
      'cat_all_video': 'تمام ویڈیوز ڈاؤن لوڈ کریں',
      'cat_insta': 'انسٹا ڈاؤن لوڈ',
      'cat_fb': 'ایف بی ڈاؤن لوڈ',
      'cat_tiktok': 'ٹک ٹاک ڈاؤن لوڈ',
      'cat_twitter': 'ٹویٹر ڈاؤن لوڈ',
      'next_btn': 'اگلا',
      'home_disclaimer': 'یہ ایپ کوئی مواد ہوسٹ نہیں کرتی۔ تمام ڈاؤن لوڈز عوامی طور پر شیئر کیے گئے لنکس سے ہیں۔',
      'link_hint': 'یہاں ویڈیو لنک پیسٹ کریں',
      'paste_btn': 'پیسٹ کریں',
      'download_btn': 'ڈاؤن لوڈ کریں',
      'supported_socials': 'معاون سوشل',
      'how_to_download': 'کیسے ڈاؤن لوڈ کریں؟',
      'downloads_title': 'ڈاؤن لوڈز',
      'downloads_empty': 'ابھی تک کوئی ڈاؤن لوڈ نہیں',
      'social_facebook': 'فیس بک',
      'social_instagram': 'انسٹاگرام',
      'social_whatsapp': 'واٹس ایپ',
      'social_pinterest': 'پنٹرسٹ',
      'media_photos': 'تصاویر',
      'media_video': 'ویڈیو',
    },
    const Locale('vi', 'VN'): {
      'lan': 'Tiếng Việt',
      'select_language': 'Chọn ngôn ngữ',
      'perm_title': 'Quyền truy cập',
      'perm_heading': 'Quyền đọc và ghi',
      'perm_subtitle': 'Ứng dụng này cần quyền lưu trữ để truy cập thư viện ảnh của bạn. Nếu không có quyền này, ứng dụng sẽ không hoạt động đúng cách.',
      'allow_access': 'Cho phép truy cập',
      'privacy_title': 'Chính sách quyền riêng tư',
      'privacy_intro': 'Khi bạn sử dụng ứng dụng của chúng tôi, chính sách quyền riêng tư này mô tả thông tin chúng tôi thu thập và cách chúng tôi sử dụng thông tin đó. Quyền riêng tư của bạn rất quan trọng với chúng tôi.',
      'privacy_notif_title': 'Thông báo',
      'privacy_notif_body': 'Quyền này được dùng để gửi cho bạn lời nhắc và các cập nhật quan trọng.',
      'privacy_photos_title': 'Ảnh và video',
      'privacy_photos_body': 'Quyền này cho phép ứng dụng truy cập thư viện ảnh và video trên thiết bị của bạn để ứng dụng hoạt động đúng cách.',
      'privacy_network_title': 'Truy cập mạng đầy đủ',
      'privacy_network_body': 'Dùng để nhận thông báo cập nhật và truy cập nhãn phân loại ứng dụng.',
      'privacy_agree_checkbox': 'Tôi đã đọc và chấp nhận chính sách quyền riêng tư',
      'agree_next': 'Đồng ý & Tiếp tục',
      'onboard_title_1': 'XVX Trình tải video 4K',
      'onboard_sub_1': 'Tải video từ nhiều nền tảng khác nhau',
      'onboard_title_2': 'Dán & Tải xuống',
      'onboard_sub_2': 'Dán liên kết và tải video xuống',
      'onboard_title_3': 'Tải xuống nhanh hơn 3 lần',
      'onboard_sub_3': 'Tải video nhanh hơn 3 lần so với bình thường',
      'personalized_title': 'Thông tin cá nhân hóa',
      'personalized_subtitle': 'Nhận cập nhật và nội dung được thiết kế riêng cho bạn',
      'select_gender': 'Chọn giới tính',
      'gender_female': 'Nữ',
      'gender_male': 'Nam',
      'gender_warning': 'Sau khi chọn giới tính, bạn sẽ không thể thay đổi! Hãy chọn cẩn thận trước khi tiếp tục.',
      'select_age_range': 'Chọn độ tuổi',
      'select_age_subtitle': 'Chọn một độ tuổi để khám phá những người hoặc nội dung phù hợp nhất với bạn',
      'age_18_24': '18 - 24',
      'age_25_31': '25 - 31',
      'age_32_39': '32 - 39',
      'age_40_plus': '40 +',
      'select_category': 'Chọn danh mục',
      'select_category_subtitle': 'Chọn danh mục để khám phá những người hoặc nội dung phù hợp nhất với bạn',
      'cat_all_video': 'Tải tất cả video',
      'cat_insta': 'Tải Insta',
      'cat_fb': 'Tải FB',
      'cat_tiktok': 'Tải Tik Tok',
      'cat_twitter': 'Tải Twitter',
      'next_btn': 'Tiếp theo',
      'home_disclaimer': 'Ứng dụng này không lưu trữ bất kỳ nội dung nào. Tất cả tải xuống đều từ các liên kết được chia sẻ công khai.',
      'link_hint': 'Dán liên kết video vào đây',
      'paste_btn': 'Dán',
      'download_btn': 'Tải xuống',
      'supported_socials': 'Mạng xã hội hỗ trợ',
      'how_to_download': 'Cách tải xuống?',
      'downloads_title': 'Tải xuống',
      'downloads_empty': 'Chưa có mục tải xuống nào',
      'social_facebook': 'Facebook',
      'social_instagram': 'Instagram',
      'social_whatsapp': 'Whatsapp',
      'social_pinterest': 'Pinterest',
      'media_photos': 'Ảnh',
      'media_video': 'Video',
    },
  };

  static Locale localeFor(String code) {
    return data.keys.firstWhere(
      (l) => l.languageCode == code,
      orElse: () => const Locale('en', 'US'),
    );
  }
}